infrastructureDefinition:
  name: Prod-Infra
  identifier: ProdInfra
  orgIdentifier: default
  projectIdentifier: default_project
  environmentRef: Production
  deploymentType: NativeHelm
  type: KubernetesDirect
  spec:
    connectorRef: VMHostedCluster
    namespace: <+pipeline.variables.namespace>
    releaseName: my-portfolio-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: false
