pipeline:
  name: Build Portfolio Image
  identifier: Build_Portfolio_Image
  projectIdentifier: default_project
  orgIdentifier: default
  tags:
    version: v1.1.<+pipeline.sequenceId>
  stages:
    - stage:
        name: docker build
        identifier: docker_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build And Push Docker
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Docker_Connector
                    repo: kundansingh27feb/portfolio-app
                    tags:
                      - v1.1.<+pipeline.sequenceId>
                    dockerfile: docker/Dockerfile
              - step:
                  type: GitClone
                  name: Clone Repo
                  identifier: Clone_Repo
                  spec:
                    connectorRef: account.Github_OAuth_1743922765736
                    repoName: kundansingh27feb/portfolio-app
                    submoduleStrategy: recursive
                    prCloneStrategy: SourceBranch
                    build:
                      type: branch
                      spec:
                        branch: main
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        delegateSelectors:
          - helm-delegate
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1743922765736
        repoName: kundansingh27feb/portfolio-app
        build: <+input>
