pipeline:
  name: Build Portfolio Image
  identifier: Build_Portfolio_Image
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: docker build
        identifier: docker_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: VMHostedCluster
              namespace: portfolio
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Docker_Connector
                    repo: kundansingh27feb/portfolio-app
                    tags:
                      - latest
                    dockerfile: docker/Dockerfile
        delegateSelectors:
          - helm-delegate
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1743922765736
        repoName: kundansingh27feb/portfolio-app
        build: <+input>
