pipeline:
  name: Build Portfolio Image
  identifier: Build_Portfolio_Image
  projectIdentifier: default_project
  orgIdentifier: default
  tags:
    version: v1.1.<+pipeline.sequenceId>
  stages:
    - stage:
        name: docker build
        identifier: docker_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build And Push Docker
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Docker_Connector
                    repo: kundansingh27feb/portfolio-app
                    tags:
                      - v1.1.<+pipeline.sequenceId>
                    dockerfile: docker/Dockerfile
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        delegateSelectors:
          - helm-delegate
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    delegateSelectors:
                      - helm-delegate
                    source:
                      type: Inline
                      spec:
                        script: myImage=v1.1.<+pipeline.sequenceId>
                    environmentVariables: []
                    outputVariables:
                      - name: myImage
                        type: String
                        value: v1.1.<+pipeline.sequenceId>
                    outputAlias:
                      scope: Pipeline
                      key: myImage
                  timeout: 10m
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1743922765736
        repoName: kundansingh27feb/portfolio-app
        build: <+input>
